"""
step16b_export_pngs.py

Exports PNG versions of every interactive Plotly figure in step16/interactive/.
Generates three sets:
  - step16/interactive/human/*.png    — human-coded (n=86)  PRIMARY OUTPUT
  - step16/interactive/llm/*.png      — LLM corpus (n=2,368)
  - step16/interactive/compare/*.png  — side-by-side comparison

Also copies the LLM PNGs already generated by step16 into step16/interactive/llm/
for a consistent folder structure.

Run: conda run -n ilri01 python scripts/step16b_export_pngs.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import plotly.graph_objects as go

OUT_ROOT  = Path(__file__).resolve().parent / "outputs" / "step16"
INTER     = OUT_ROOT / "interactive"
HUMAN_J   = INTER / "human"
COMPARE_J = INTER / "compare"
LLM_PNG   = INTER / "llm"
HUMAN_PNG = INTER / "human"     # PNGs go alongside JSONs in same folder
COMP_PNG  = INTER / "compare"

LLM_PNG.mkdir(exist_ok=True)

# Figure dimensions: (width, height) in pixels at scale=2
DIMS: dict[str, tuple[int, int]] = {
    "evidence_gap_map":  (1100, 700),
    "domain_venn":       (900,  560),
    "domain_heatmap":    (1000, 560),
    "geographic_map":    (1000, 520),
    "geographic_bar":    (900,  480),
    "methodology":       (900,  460),
    "temporal_trends":   (900,  460),
    "equity":            (900,  440),
    "domain_type":       (900,  440),
    "producer_type":     (900,  440),
}


def export_json_to_png(json_path: Path, png_path: Path, w: int, h: int) -> None:
    with open(json_path, encoding="utf-8") as f:
        fig = go.Figure(json.load(f))
    fig.write_image(str(png_path), width=w, height=h, scale=2)
    kb = png_path.stat().st_size // 1024
    print(f"  {png_path.name}  ({kb} KB)")


def export_track(src_dir: Path, dst_dir: Path, label: str) -> None:
    dst_dir.mkdir(exist_ok=True)
    print(f"\n── {label} ({src_dir.name}/) ──")
    for json_path in sorted(src_dir.glob("*.json")):
        name = json_path.stem
        w, h = DIMS.get(name, (1000, 560))
        png_path = dst_dir / f"{name}.png"
        try:
            export_json_to_png(json_path, png_path, w, h)
        except Exception as e:
            print(f"  WARN {name}: {e}")


def copy_llm_pngs() -> None:
    """Copy step16/*.png → step16/interactive/llm/ for consistent access."""
    print(f"\n── LLM (copy from step16/) ──")
    for src in sorted(OUT_ROOT.glob("*.png")):
        if src.name == "saturation.png":
            continue  # belongs to step15c output
        dst = LLM_PNG / src.name
        shutil.copy2(src, dst)
        kb = dst.stat().st_size // 1024
        print(f"  {dst.name}  ({kb} KB)")


def main() -> None:
    print("step16b: Exporting PNGs for human / compare tracks...")

    # Human
    export_track(HUMAN_J,   HUMAN_PNG, "Human (n=86) — PRIMARY")
    # Compare
    export_track(COMPARE_J, COMP_PNG,  "Compare (human vs LLM)")
    # LLM — copy existing PNGs
    copy_llm_pngs()

    print(f"\nDone. PNG folders:")
    print(f"  Human:   {HUMAN_PNG}")
    print(f"  Compare: {COMP_PNG}")
    print(f"  LLM:     {LLM_PNG}")


if __name__ == "__main__":
    main()
